### ISSUE TITLE
Set a Poke user agent string

### ISSUE THREAD

**Issue by urcadox** [warp-poke/http-rust-agent#1]
This agent should at least send a custom user agent string with Poke in it.

Better yet, it should be configurable.

**Comment by NotBad4U** [comment]
Can we close this one?

**Comment by urcadox** [comment]
Well, is it done?

**Comment by urcadox** [comment]
I just edited the title and the description to make this clearer.

**Comment by NotBad4U** [comment]
The synthax of user-agent is:
> User-Agent: \<product\> / \<product-version\> \<comment\>

So something like: `User-Agent: Poke` is enough ?

**Comment by urcadox** [comment]
`Poke / <version OR commitid>` would be fine, yes.
